---
layout: cv
title: Makay Crandall
---
# Isaac Newton
Assistant Networking Engineer, Computer Science Student at BYUI

<div id="webaddress">
<a href="isaac@applesdofall.org">isaac@applesdofall.org</a>
| <a href="http://en.wikipedia.org/wiki/Isaac_Newton">My wikipedia page</a>
</div>


## Currently

Studying Computer Science

### Specialized in

Web Development, Data Science, and Python


### Research interests

Data Analysis, Web Design front&Back End


## Education

`2016-2019`
__Spanish Springs High School__

`2023 - now`
__Brigham Young University Idaho__

- Sizar

`1667 - death`
__Trinity College, Cambridge__

- Fellow



## Awards

`2012`
President, *Royal Society*, London, UK

Associate, *French Academy of Science*, Paris, France



## Publications

<!-- A list is also available [online](http://scholar.google.co.uk/citations?user=LTOTl0YAAAAJ) -->

### Journals

`1669`
Newton Sir I, De analysi per æquationes numero terminorum infinitas. 

`1669`
Lectiones opticæ.

etc. etc. etc.

### Patents

`2012`
Infinitesimal calculus for solutions to physics problems, [SMBC](http://www.techdirt.com/articles/20121011/09312820678/if-patents-had-been-around-time-newton.shtml) patent 001


## Occupation

`June 2017-September 2017`
__Redhawk Golf Coarse__, Sparks, Nevada

`June 2019–January 2020 & February 2023– August 2023`
__Geodis, Inventory__, Reno, Nevada

`June 2019–January 2020 & February 2023– August 2023`
__Assistant Networking Engineer__, BYUI

<!-- ### Footer

Last updated: May 2013 -->